var Quiz = [		["A Kripke-frame is a tuple", 1,
         "\\( (W, R) \\)",
         "\\((W, R, Prop)\\)",
         "\\((W, R, Prop, U, D)\\)",
         "\\((W, R, Prop, U, D,|-|)\\)"
		 ],
		["A general frame is a tuple", 2,
         "\\((W, R)\\)",
         "\\((W, R, Prop)\\)",
         "\\((W, R, Prop, U, D)\\)",
         "\\((W, R, Prop, U, D,|-|)\\)"
		 ],
		["A model structure is a tuple", 3,
         "\\((W, R)\\)",
         "\\((W, R, Prop)\\)",
         "\\((W, R, Prop, U, D)\\)",
         "\\((W, R, Prop, U, D,|-|)\\)"
		 ],
		["A premodel is a tuple", 4,
         "\\((W, R)\\)",
         "\\((W, R, Prop)\\)",
         "\\((W, R, Prop, U, D)\\)",
         "\\((W, R, Prop, U, D,|-|)\\)"
		 ],
		["A model is a tuple", 4,
         "\\((W, R)\\)",
         "\\((W, R, Prop)\\)",
         "\\((W, R, Prop, U, D)\\)",
         "\\((W, R, Prop, U, D,|-|)\\)"
		 ],
 		["\\(Ea\\) is " , 1,
         "\\(\\{w \\in W \\, :\\, a \\in Dw\\}\\)",
         "\\(\\{w \\in W \\, :\\, a \\in U\\}\\)",
         "\\( a \\approx a\\), where \\(\\approx\\) is the identity ",
         "\\( \\exists x  x\\approx a\\), where \\(\\approx\\) is the identity "
		 ],
 		["Is it true in all model structure that \\(Ea\\in Prop\\) for all \\(a\\in U\\)?" , 2,
         "Yes",
         "No"
		 ],
 		["\\(X\\downarrow\\) is " , 8,
         "\\(\\bigcap \\{Y \\in \\wp W \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcap \\{Y \\in \\wp W \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcup \\{Y \\in \\wp W \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcup \\{Y \\in \\wp W \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcap \\{Y \\in Prop \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcap \\{Y \\in Prop \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcup \\{Y \\in Prop \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcup \\{Y \\in Prop \\, :\\, Y\\subseteq X\\}\\)"
         ],
 		["\\(X\\uparrow\\) is " , 5,
         "\\(\\bigcap \\{Y \\in \\wp W \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcap \\{Y \\in \\wp W \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcup \\{Y \\in \\wp W \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcup \\{Y \\in \\wp W \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcap \\{Y \\in Prop \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcap \\{Y \\in Prop \\, :\\, Y\\subseteq X\\}\\)",
         "\\(\\bigcup \\{Y \\in Prop \\, :\\, X\\subseteq Y\\}\\)",
         "\\(\\bigcup \\{Y \\in Prop \\, :\\, Y\\subseteq X\\}\\)"
         ],
 		["Which one is always true?" , 2,
         "\\(X\\downarrow = X = X\\uparrow\\)",
         "\\(X\\downarrow \\subseteq X \\subseteq X\\uparrow\\)",
         "\\(X\\downarrow \\subset   X \\subseteq X\\uparrow\\)",
         "\\(X\\downarrow \\subseteq X \\subset   X\\uparrow\\)",
         "\\(X\\downarrow \\subset   X \\subset   X\\uparrow\\)",
         "\\(X\\downarrow \\supseteq X \\supseteq X\\uparrow\\)",
         "\\(X\\downarrow \\supset   X \\supseteq X\\uparrow\\)",
         "\\(X\\downarrow \\supseteq X \\supset   X\\uparrow\\)",
         "\\(X\\downarrow \\supset   X \\supset   X\\uparrow\\)",
         "\\(X\\downarrow \\subseteq X \\supseteq X\\uparrow\\)",
         "\\(X\\downarrow \\subset   X \\supseteq X\\uparrow\\)",
         "\\(X\\downarrow \\subseteq X \\supset   X\\uparrow\\)",
         "\\(X\\downarrow \\subset   X \\supset   X\\uparrow\\)",
         "\\(X\\downarrow \\supseteq X \\subseteq X\\uparrow\\)",
         "\\(X\\downarrow \\supset   X \\subseteq X\\uparrow\\)",
         "\\(X\\downarrow \\supseteq X \\subset   X\\uparrow\\)",
         "\\(X\\downarrow \\supset   X \\subset   X\\uparrow\\)"
         ],
 		["Which one is always true?" , 5,
         "\\(X\\downarrow\\in Prop\\)",
         "\\(X\\downarrow\\in Prop\\) if \\(X\\in Prop\\)" ,
         "\\(X\\uparrow\\in Prop\\)" ,
         "\\(X\\uparrow\\in Prop\\) if \\(X\\in Prop\\)" ,
         "neither" 
         ],
		["\\(\\bigsqcup \\mathcal Z\\) is", 1,
         "\\( \\left(\\bigcup \\mathcal Z\\right) \\uparrow \\)",
         "\\( \\left(\\bigcup \\mathcal Z\\right) \\downarrow \\)",
         "\\( \\left(\\bigcap \\mathcal Z\\right) \\uparrow \\)",
         "\\( \\left(\\bigcap \\mathcal Z\\right) \\downarrow \\)"
		],
		["\\(\\sqcap \\mathcal Z\\) is", 3,
         "\\( \\left(\\bigcup \\mathcal Z\\right) \\downarrow \\)",
         "\\( \\left(\\bigcup \\mathcal Z\\right) \\uparrow \\)",
         "\\( \\left(\\bigcap \\mathcal Z\\right) \\downarrow \\)",
         "\\( \\left(\\bigcap \\mathcal Z\\right) \\uparrow \\)"
		],
		["The lemma \\(X\\in Prop \\Rightarrow \\left(\\bigsqcup \\mathcal Z\\subseteq X \\iff \\bigcup \\mathcal Z\\subseteq X  \\right) \\) says that", 3,
         "\\(\\bigsqcup\\) and \\(\\bigcup\\) can be the same",
         "\\(\\bigsqcup\\) and \\(\\bigcup\\) are indistinguishable for propositions",
         "\\(\\bigsqcup\\) and \\(\\bigcup\\) are indistinguishable for admissible propositions"
		 ],
		["If \\(\\bigcup \\mathcal Z\\in Prop\\) is admissible, then", 3,
         "\\( \\bigcup \\mathcal Z \\subseteq \\bigsqcup \\mathcal Z \\)",
         "\\( \\bigcup \\mathcal Z \\supseteq \\bigsqcup \\mathcal Z \\)",
         "\\( \\bigcup \\mathcal Z = \\bigsqcup \\mathcal Z \\)"
		 ],
		["\\(\\bigsqcup_{i\\in I}\\bigsqcup_{j\\in J} X_{ij}=\\bigsqcup_{j\\in J}\\bigsqcup_{i\\in I} X_{ij}\\) is ", 3,
         "never true",
         "sometimes true, sometimes not",
         "always true"
		 ],
		["In a premodel, the meaning of an \\(n\\)-ary predicate symbol is ", 4,
         "a set \\(|P|^{\\mathcal M} = \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: W \\to \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: Prop \\to \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: U^n \\to \\wp (W)\\) ",
         "a function \\(|P|^{\\mathcal M}: U^n \\to Prop\\) "
		 ],
		["In a model, the meaning of an \\(n\\)-ary predicate symbol is ", 5,
         "a set \\(|P|^{\\mathcal M} = \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: W \\to \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: Prop \\to \\wp (U^n)\\) ",
         "a function \\(|P|^{\\mathcal M}: U^n \\to \\wp (W)\\) ",
         "a function \\(|P|^{\\mathcal M}: U^n \\to Prop\\) "
		 ],
		["In a model, the meaning of an \\(n\\)-ary function symbol is ", 4,
         "in each world \\(w\\) a function \\(Dw^n\\to Dw\\) ",
         "in each world \\(w\\) a function \\(U^n\\to Dw\\) ",
         "in each world \\(w\\) a function \\(Dw^n\\to U\\) ",
         "a function \\(U^n\\to U\\) "
		 ],
		 ["Are the constants rigid designators?", 1,
         "Yes.",
		 "No."
		 ],
		 ["Are the terms rigid designators?", 1,
         "Yes.",
		 "No."
		 ],
		["A model, by definition, is ", 2,
		 "A premodel in which the meaning of \\(n\\)-ary predicates \\(P\\) are \\(|P|^{\\mathcal M}: U^n \\to Prop\\), that is, the atomic sentences are all admissible. ",
		 "A premodel in which the meaning of formulas \\(\\varphi\\) having \\(n\\) free variables are \\(|\\varphi|^{\\mathcal M}: U^n \\to Prop\\), that is, the formulas are all admissible. "
		 ],
		["In a premodel, ", 4,
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a model, ", 4,
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a Kripkean premodel, ", 1,
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\forall x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\forall a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a premodel, ", 3,
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a model, ", 3,
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a Kripkean premodel, ", 1,
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\forall X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\forall w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 "\\(\\mathcal M, w, f \\models \\exists x \\varphi \\iff (\\exists X\\in Prop)\\left(w\\in X \\quad \\mathrm{and}\\quad (\\exists w'\\in X)(\\exists a\\in Dw') \\mathcal M , w', f[a/x] \\models \\varphi \\right)\\)",
		 ],
		["In a premodel, ", 2,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftrightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
		["In a premodel, ", 3,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftrightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
		["In a model, ", 2,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftrightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
		["In a model, ", 3,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftrightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
 		["In a Kripkean premodel, ", 4,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\not \\Rightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\varphi \\Leftrightarrow (\\forall a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
		["In a Kripkean premodel, ", 4,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\not \\Rightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\exists x \\varphi \\Leftrightarrow (\\exists a\\in Dw) \\mathcal M , w, f[a/x] \\models \\varphi \\)",
		 ],
		["In a premodel, ", 2,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}  \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftrightarrow Dw=\\emptyset \\)<br>",
		 ],
		["In a model, ", 2,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}  \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftrightarrow Dw=\\emptyset \\)<br>",
		 ],
		["In a Kripkean premodel, ", 4,
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}  \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F}\\not \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\not \\Rightarrow Dw=\\emptyset \\) <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    and \\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftarrow Dw=\\emptyset\\)<br>",
		 "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\(\\mathcal M, w, f \\models \\forall x \\mathsf{F} \\Leftrightarrow Dw=\\emptyset \\)<br>",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li>. ", 1,
		 "Every existence set \\(En\\) is admissible, i.e., \\((\\forall n\\in U) En\\in Prop\\)",
		 "Some existence sets \\(En\\) are admissible, some are not, i.e., \\((\\exists n,m\\in U) En\\in Prop, Em\\notin Prop\\).",
		 "No existence set \\(En\\) is admissible, i.e., \\((\\forall n\\in U) En\\notin Prop\\)",
		 ],
		["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li>", 3,
		 "\\(\\{0\\}\\!\\!\\downarrow=\\{0\\}\\)",
		 "\\(\\{0\\}\\!\\!\\downarrow=0\\)",
		 "\\(\\{0\\}\\!\\!\\downarrow=\\emptyset\\)",
		 "\\(\\{0\\}\\!\\!\\downarrow=\\{X\\, :\\, X \\ \\ \\mathrm{is \\ \\ finite}\\}\\)",
		 ],
		["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). ", 2,
		 "\\(\\mathcal Z \\in Prop\\)",
		 "\\(\\mathcal Z \\subseteq Prop\\)",
		 "\\(\\mathcal Z \\not\\subseteq Prop\\)",
		 ],
		["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). ", 1,
		 "\\(\\bigcap\\mathcal Z =\\{0\\}\\)",
		 "\\(\\bigcap\\mathcal Z =0\\)",
		 "\\(\\bigcap\\mathcal Z =\\emptyset\\)",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). ", 3,
		 "\\(\\sqcap\\mathcal Z =\\{0\\}\\)",
		 "\\(\\sqcap\\mathcal Z =0\\)",
		 "\\(\\sqcap\\mathcal Z =\\emptyset\\)",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). ", 2,
		 "\\(\\bigcap\\mathcal Z \\in Prop\\)",
		 "\\(\\bigcap\\mathcal Z \\notin Prop\\)",
		 "\\(\\bigcap\\mathcal Z \\subseteq Prop\\)",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). ", 1,
		 "\\(\\sqcap\\mathcal Z \\in Prop\\)",
		 "\\(\\sqcap\\mathcal Z \\notin Prop\\)",
		 "\\(\\sqcap\\mathcal Z \\subseteq Prop\\)",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li> ", 3,
		 "For all variable-assignment \\(f\\) and interpretation \\(|-|^{\\mathcal M}\\) it is true that \\(\\mathcal M ,w_0, f\\models \\forall x \\mathsf{F}\\)",
		 "There is an variable-assignment \\(f\\) and interpretation \\(|-|^{\\mathcal M}\\) such that \\(\\mathcal M ,w_0, f\\models \\forall x \\mathsf{F}\\)",
		 "There is no variable-assignment \\(f\\) and interpretation \\(|-|^{\\mathcal M}\\) such that \\(\\mathcal M ,w_0, f\\models \\forall x \\mathsf{F}\\)",
		 ],
		 ["Consider the following model stucture (Example 1.5.2): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li> ", 3,
		 "Every premodel builded on this model structure is Kripkean",
		 "There is premodel builded on this model structure which is Kripkean",
		 "No premodel builded on this model structure is Kripkean",
		 ],
		 ["Consider the following model structure (Example 1.6.6): <br><br> \\( \\mathcal S = (W,R, Prop,U,D) \\) <br><br>where <ul><li>\\(W=\\{w_i \\, :\\, i\\in\\omega\\}\\),</li><li> \\(R=\\varnothing\\),</li><li>  \\( Prop = \\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X\\}\\cup (W-\\{ X\\subseteq \\wp (W) \\,:\\, |X| < \\omega , \\, 0\\notin X \\})\\), that is, the finite sets that do not contain \\(0\\) and their complements,</li><li>\\(U=\\omega\\),</li><li>\\( D(w_n)=\\left\\{ \\begin{array}{l} \\varnothing \\ \\mathrm{if}\\  n=0 \\\\ \{n\} \\ \\mathrm{otherwise} \\end{array} \\right.  \\) </li><br> Let \\(\\mathcal Z =\\{ W-\\{n\\} \\, : \\, n>0 \\}\\). <br> If we take the intepretation \\(|-|^{\\mathcal M}\\) which assigns to each predicate letter the empty function, i.e., for all \\( P \\), \\( |P|(n_1,\\dots, n_k)=\\emptyset \\), then", 3,
		 "\\( \\mathcal M = (W,R, Prop,U,D, |-|^{\\mathcal M}) \\) won't be a premodel.",
		 "\\( \\mathcal M = (W,R, Prop,U,D, |-|^{\\mathcal M}) \\) will be a premodel, but it won't be a model or a Kripkean premodel.",
		 "\\( \\mathcal M = (W,R, Prop,U,D, |-|^{\\mathcal M}) \\) will be a model, but it won't be Kripkean.",
		 "\\( \\mathcal M = (W,R, Prop,U,D, |-|^{\\mathcal M}) \\) will be a Kripkean premodel, but it won't be model.",
		 "\\( \\mathcal M = (W,R, Prop,U,D, |-|^{\\mathcal M}) \\) will be a Kripkean model.",
		 ],
		 ];