var Quiz = [
		["Which one of the followings is <b>not</b> valid on all frames?", 2,
         "\\(\\mathbf G (\\varphi \\land \\psi) \\rightarrow (\\mathbf G \\varphi \\land \\mathbf G \\psi )\\)",
         "\\(\\mathbf G (\\varphi \\lor \\psi) \\rightarrow  (\\mathbf G \\varphi \\lor \\mathbf G \\psi )\\)",
         "\\(\\mathbf G (\\varphi \\land \\psi) \\leftarrow  (\\mathbf G \\varphi \\land \\mathbf G \\psi )\\)",
         "\\(\\mathbf G (\\varphi \\lor \\psi) \\leftarrow  (\\mathbf G \\varphi \\lor \\mathbf G \\psi )\\)"],
		["Which one of the followings is <b>not</b> valid on all frames", 3,
         "\\(\\mathbf F (\\varphi \\land \\psi) \\rightarrow (\\mathbf F \\varphi \\land \\mathbf F \\psi )\\)",
         "\\(\\mathbf F (\\varphi \\lor \\psi) \\rightarrow  (\\mathbf F \\varphi \\lor \\mathbf F \\psi )\\)",
         "\\(\\mathbf F (\\varphi \\land \\psi) \\leftarrow  (\\mathbf F \\varphi \\land \\mathbf F \\psi )\\)",
         "\\(\\mathbf F (\\varphi \\lor \\psi) \\leftarrow  (\\mathbf F \\varphi \\lor \\mathbf F \\psi )\\)"],
		["Which one of the followings is <b>not</b> valid on all frames?", 2,
         "\\(\\mathbf G (\\varphi \\rightarrow \\psi) \\rightarrow (\\mathbf G \\varphi \\rightarrow \\mathbf G \\psi )\\)",
         "\\(\\mathbf G (\\varphi \\rightarrow \\psi) \\leftarrow (\\mathbf G \\varphi \\rightarrow \\mathbf G \\psi )\\)"],
		["Which one of the followings is <b>not</b> valid on all flow of time-frames (STO-s, strict total orders)?", 2,
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G\\mathbf F\\psi\\)",
         "\\( \\mathbf G \\varphi \\rightarrow \\varphi\\)",
         "\\( \\underline{\\mathbf G}\\varphi \\rightarrow \\varphi\\)",
		 "\\( \\mathbf F \\varphi \\rightarrow \\mathbf F\\mathbf F \\varphi\\)",
         "\\( \\mathbf P \\varphi \\rightarrow \\mathbf P\\mathbf P \\varphi\\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
         "\\( \\mathbf G (\\underline {\\mathbf G} \\varphi \\rightarrow \\psi )\\lor \\mathbf G (\\underline {\\mathbf G} \\psi \\rightarrow \\varphi )\\)"],
		["Which one of the followings is <b>not</b> valid on all temporal frames?", 1,
         "\\( \\varphi \\rightarrow \\mathbf G\\mathbf F\\varphi\\)",
         "\\( \\varphi \\rightarrow \\mathbf G\\mathbf P\\varphi\\)",
         "\\( \\varphi \\rightarrow \\mathbf H\\mathbf F\\varphi\\)",
         "\\( \\mathbf F \\mathbf H\\varphi \\rightarrow \\varphi\\)"],
		["Which one of the followings is valid <b>only</b> on those frames that do not have branchings to the past?", 4,
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G\\mathbf F\\psi\\)",
         "\\( \\varphi \\rightarrow \\mathbf H\\mathbf P\\varphi\\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
         "\\( \\mathbf H (\\underline {\\mathbf H} \\varphi \\rightarrow \\psi )\\lor \\mathbf H (\\underline {\\mathbf H} \\psi \\rightarrow \\varphi )\\)"],
		["Which one of the followings is valid on all strict partial orders (SPO-s)?", 4,
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G\\mathbf F\\psi\\)",
         "\\( \\varphi \\rightarrow \\mathbf G\\mathbf F\\varphi\\)",
         "\\( \\mathbf G \\varphi \\rightarrow \\varphi\\)",
		 "\\( \\mathbf F \\varphi \\rightarrow \\mathbf F\\mathbf F \\varphi\\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
         "\\( \\mathbf G (\\underline {\\mathbf G} \\varphi \\rightarrow \\psi )\\lor \\mathbf G (\\underline {\\mathbf G} \\psi \\rightarrow \\varphi )\\)"],
		["In which structure is it true that \\(\\forall w,v(w\\leq v \\liff \\lnot w > v) \\)?", 5,
         "It is true for any frames",
         "It is true for SPO-s",
         "It is true for forests (treelike SPO-s)",
         "It is true for trees",
         "It is true for STO-s (flow of time frames)"],
		["Which one is <b>not true</b>?", 1,
         "A frame is connected iff every two element is related to each other with the alternative relation.",
         "A frame is connected iff every two element is related to each other with the reflexive-transitive-symmetric closure of the alternative relation.",
         "A frame is connected iff every two element is accessible with finitely many (forward or backward) steps on the alternative relation.",
         "A frame is connected iff every two element is accessible with finitely many (forward or backward) steps on the reflexive-transitive-symmetric closure of the alternative relation."],
		["Which one is a standard translation of the formula \\( \\varphi  \\; = \\; \\mathbf G p \\rightarrow \\mathbf F p \\)?", 2,
         "\\(\\mathrm{ST}_x (\\varphi) =  \\forall y (y>x \\rightarrow p) \\rightarrow \\exists y (y>x \\land p) \\)",
         "\\(\\mathrm{ST}_x (\\varphi) =  \\forall y (y>x \\rightarrow P(y)) \\rightarrow \\exists y (y>x \\land P(y)) \\)",
         "\\(\\mathrm{ST}_x (\\varphi) =  \\forall y (y>x \\rightarrow P(x)) \\rightarrow \\exists y (y>x \\land P(x)) \\)",
         "\\(\\mathrm{ST}_x (\\varphi) =  \\forall y (y < x \\rightarrow P(y)) \\rightarrow \\exists y (y < x \\land P(y)) \\)",
         "\\(\\mathrm{ST}_x (\\varphi) =  \\forall y (y < x \\rightarrow p ) \\rightarrow \\exists y (y < x \\land p) \\)",
         ],
		["On which frames is the so-called McKinsey formula \\( M  \\; = \\; \\mathbf G \\mathbf F p \\rightarrow \\mathbf F \\mathbf G p \\) valid?", 4,
         "It is valid on those frames that have the following first-order property: \\( ( \\forall y>x ) (\\exists z>y) z>x \\rightarrow (\\exists y>x ) (\\forall z>y) z>x )\\)",
         "It is valid on those frames that have the following first-order property: \\( \\forall x (( \\forall y>x ) (\\exists z>y) P(z) \\rightarrow (\\exists y>x ) (\\forall z>y) P(z) )\\)",
         "It is valid on those frames that have the following first-order property: \\( \\forall x (( \\forall y>x ) (\\exists z>y) P(x) \\rightarrow (\\exists y>x ) (\\forall z>y) P(x) )\\)",
         "It is valid on those frames that have the following second-order property: \\( \\forall P\\forall x (( \\forall y>x ) (\\exists z>y) P(z) \\rightarrow (\\exists y>x ) (\\forall z>y) P(z) )\\)",
         ],
		["Which formula defines transitivity, that is, the property \\( x < y < z \\rightarrow x < z \\)?", 3,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
		["Which formula defines seriality, that is, the property \\( \\forall x \\exists y \\; x < y \\)?", 2,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
		["Which formula defines non-branching to the future, that is, the property \\( y > x < z \\rightarrow y < z \\lor  y > z \\lor y=z \\)?", 6,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
		["Which formula defines density, that is, the property \\( x < z \\rightarrow \\exists y \\; x < y < z \\)?", 4,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
		["Which formula defines confluence/convergence, that is, the property \\( y > x < z \\rightarrow \\exists u \\; y < u > z \\)?", 5,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
		 ["Which formula defines the property that every world sees a dead end/final world, i.e., \\( \\forall x(\\exists y>x) \\lnot \\exists z \\; z > y\\)?", 1,
         "\\(\\mathbf F \\mathbf G \\bot \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf F \\varphi  \\)",
         "\\(\\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf G \\varphi  \\)",
         "\\(\\mathbf G \\mathbf G \\varphi \\rightarrow \\mathbf G \\varphi  \\)",
         "\\(\\mathbf F \\mathbf G \\varphi \\rightarrow \\mathbf G \\mathbf F\\varphi  \\)",
         "\\((\\mathbf F \\varphi \\land \\mathbf F \\psi )\\rightarrow (\\mathbf F (\\varphi \\land \\mathbf F \\psi ) \\lor \\mathbf F (\\mathbf F \\varphi \\land \\psi ) \\lor \\mathbf F (\\varphi \\land \\psi))\\)",
		 ],
];