var kep = '<table border =0><td><img src="http://phil.elte.hu/~attila/courses/FOML/modell.png"></td></table>'
var Quiz = [
		["\\([R](X)\\) is defined as ", 2,
         "\\(\\{ y \\in W \\, : \\, (\\forall x R y ) x\\in X \\}\\)",
         "\\(\\{ y \\in W \\, : \\, \\forall x( yRx \\rightarrow x\\in X) \\}\\)",
         "\\(\\{ y \\in W \\, : \\, (\\forall x \\in X) xRy \\}\\)",
         "\\(\\{ y \\in W \\, : \\, (\\forall x \\in X) yRx \\}\\)"],
		["Consider the model "+kep, 1,
         "\\( w_6\\in |\\Box r|^{\\mathcal M} \\)",
         "\\( w_1\\in |\\Box p|^{\\mathcal M} \\)",
         "\\( w_5\\in |\\Box r|^{\\mathcal M} \\)"],
		["Consider the model "+kep, 1,
         "\\( w_1\\in |\\Box (p\\lor q)|^{\\mathcal M} \\)",
         "\\( w_1\\in |\\Box p\\lor \\Box q|^{\\mathcal M} \\)",
         "\\( w_1\\in |\\Box r|^{\\mathcal M} \\)",],
		["Consider the model "+kep, 3,
         "\\( w_1\\in |\\Box (p\\land q)|^{\\mathcal M} \\)",
         "\\( w_1\\in |p\\lor q \\lor r|^{\\mathcal M} \\)",
         "\\( w_1\\in |\\Box \\lnot r|^{\\mathcal M} \\)"],
		["Consider the model "+kep, 2,
         "\\( |\\Box \\mathsf F|^{\\mathcal M} = \\{ w_{12}\\} \\)",
         "\\( |\\Box \\mathsf F|^{\\mathcal M} = \\{ w_3, w_9, w_{10}, w_{12}\\} \\)",
         "\\( |\\Box \\mathsf F|^{\\mathcal M} = \\varnothing \\)"],
		["Consider the model "+kep, 2,
         "\\( |\\Diamond \\mathsf F|^{\\mathcal M} = \\{ w_{12}\\} \\)",
         "\\( |\\Diamond \\mathsf F|^{\\mathcal M} = \\{ w_3, w_9, w_{10}, w_{12}\\} \\)",
         "\\( |\\Diamond \\mathsf F|^{\\mathcal M} = \\varnothing \\)"],
		["Consider the model "+kep, 2,
         "\\( |\\Diamond \\mathsf T|^{\\mathcal M} = W-\\{ w_{12}\\} \\)",
         "\\( |\\Diamond \\mathsf T|^{\\mathcal M} = W-\\{ w_3, w_9, w_{10}, w_{12}\\} \\)",
         "\\( |\\Diamond \\mathsf T|^{\\mathcal M} = W\\)"],
		["Consider the model "+kep, 1,
         "\\( |\\Box p|^{\\mathcal M} = \\{ w_2\\} \\)",
		 "\\( |\\Box p|^{\\mathcal M} = \\{ w_2, w_3\\} \\)",
		 "\\( |\\Box p|^{\\mathcal M} = \\{ w_2, w_8\\} \\)",
         "\\( |\\Box p|^{\\mathcal M} = \\{ w_2, w_3, w_8, w_9, w_{10}, w_{12}\\} \\)"],
		["\\(\\mathrm S_{\\mathcal M}\\) is ", 1,
		 "\\( \\{A \\, : \\, \\mathcal M\\models A\\}\\)",
         "\\( \\{\\mathcal M \\, : \\, \\mathcal M\\models S\\}\\)"],
		["\\(\\mathrm S_{\\mathcal F}\\) is ", 1,
		 "\\( \\{A \\, : \\, \\mathcal F\\models A\\}\\)",
         "\\( \\{\\mathcal F \\, : \\, \\mathcal F\\models S\\}\\)"],
		["\\(\\mathrm S_{\\mathscr C}\\) is ", 1,
		 "\\( \\{A \\, : \\, \\mathscr C\\models A\\}\\)",
         "\\( \\{\\mathscr C \\, : \\, \\mathscr C\\models S\\}\\)"],
		["\\(\\mathscr C_{\\mathrm S} \\) is ", 2,
		 "\\( \\{\\mathcal M \\, : \\, \\mathcal M \\models \\mathrm S\\}\\)",
		 "\\( \\{\\mathcal F \\, : \\, \\mathcal F \\models \\mathrm S\\}\\)",
		 "\\( \\{\\mathscr C \\, : \\, \\mathscr C \\models \\mathrm S\\}\\)",
		 "\\( \\{\\mathrm S \\, : \\, \\mathscr C \\models \\mathrm S\\}\\)",
		 "\\( \\{A \\, : \\, \\mathscr C \\models A\\}\\)"],
		["Which one is not closed to the uniform substitution of formulas for propositional variables?", 1,
         "\\(\\mathrm S_{\\mathcal M}\\)",
         "\\(\\mathrm S_{\\mathcal F}\\)",
         "\\(\\mathrm S_{\\mathscr C}\\)",
		 "\\(\\mathscr C_{\\mathrm S}\\)"
        ],
		["Which one is true by definition?", 1,
         "\\(\\mathrm S\\subseteq \\mathrm S_{\\mathcal C_{\\mathrm S}}\\)",
         "\\(\\mathrm S\\supseteq \\mathrm S_{\\mathcal C_{\\mathrm S}}\\)"
        ],
		["Which one means incompleteness?", 2,
         "\\(\\mathrm S\\subseteq \\mathrm S_{\\mathcal C_{\\mathrm S}}\\)",
         "\\(\\mathrm S\\supseteq \\mathrm S_{\\mathcal C_{\\mathrm S}}\\)"
        ],
		["Incompleteness (wrt. Kripkean frame semantics) can not occur in ", 1,
         "Basic modal logic",
         "Temporal logic",
         "Multi-modal logic",
         "Poly-modal logic",
         "Multi- and poly-modal logic",
		 "In any of them.",
        ],
		["Incompleteness (wrt. general frame semantics) can not occur in ", 6,
         "Basic modal logic",
         "Temporal logic",
         "Multi-modal logic",
         "Poly-modal logic",
         "Multi- and poly-modal logic",
		 "In any of them.",
        ],
		["What does Makinson's theorem [1971] say?" , 2,
         "Every consistent basic modal logic can be satisfied on a one-element frame.",
         "Every consistent basic modal logic is valid on a one-element frame.",
         "Every consistent basic modal logic has a model in which it is true.",
         "Every consistent basic modal logic has a frame in which it is valid."
		 ],
		["S.K. Thomason showed in 1972 that", 4,
         "There is a consistent basic modal logic having no models in which it is true.",
         "There is a consistent tense logic having no models in which it is true.",
         "There is a consistent basic modal logic having no frames in which it is valid.",
         "There is a consistent tense logic having no frames in which it is valid."
		 ],
 		["What is the source of incompleteness?" , 2,
         "First-order logic and Gödel's incompleteness theorem.",
         "Second-order logic and Gödel's incompleteness theorem.",
         "Henkin's general models."
		 ],
 		["In a general frame, the set of admissible propositions is a set of propositions which is" , 3,
         "closed to finite intersection and complementation",
         "closed to intersection and complementation",
         "closed to finite intersection, complementation and to the operation \\( [R] \\)",
         "closed to intersection, complementation and to the operation \\( [R] \\)"],
 		["What is the difference between a Kripke frame and a full general frame?" , 1,
         "Nothing",
         "In a full general frame not every proposition is admissible."
		 ],
 		["What is the relation between the valuations of a Kripke frame and a general frame" , 2,
         "they have nothing in common.",
         "every admissible valuation is a Kripkean valuation",
         "every Kripkean valuation is an admissible valuation",
         "they are the same."
		 ],
 		["The Jónsson-Tarski theorem [1948-1951] ensures that (choose the strongest true statement!)" , 10,
         "Every consistent basic modal propositional logic has Kripke-frames.",
         "Every consistent basic modal propositional logic has general frames.",
         "Every consistent basic modal propositional logic has Kripke-frames.",
         "Every consistent basic modal propositional logic has general frames.",
         "Every consistent multi-modal propositional logic has Kripke-frames.",
         "Every consistent multi-modal propositional logic has general frames.",
         "Every consistent poly-modal propositional logic has Kripke-frames.",
         "Every consistent poly-modal propositional logic has general frames.",
         "Every consistent multi-modal and poly-modal propositional logic has Kripke-frames.",
         "Every consistent multi-modal and poly-modal propositional logic has general frames."
		 ],
		["The converse of the Barcan Formula is", 3,
         "\\(\\Diamond \\forall x \\varphi \\rightarrow \\forall x \\Diamond \\varphi \\)",
         "\\(\\Box \\exists x \\varphi \\rightarrow \\exists x \\Box \\varphi  \\)",
         "\\(\\Box \\forall x \\varphi \\rightarrow \\forall x \\Box \\varphi \\)",
         "\\(\\forall x \\Box \\varphi \\rightarrow \\Box \\forall x \\varphi  \\)"],
 		["\\(Ea\\) is " , 1,
         "\\(\\{w \\in W \\, :\\, a \\in Dw\\}\\)",
         "\\(\\{w \\in W \\, :\\, a \\in U\\}\\)",
         "\\( a \\approx a\\), where \\(\\approx\\) is the identity ",
         "\\( \\exists x  x\\approx a\\), where \\(\\approx\\) is the identity "
		 ],
 		["What is the connection between \\(\\subseteq \\) and \\(\\Rightarrow\\)?" , 2,
         "\\(X \\subseteq Y\\) iff \\(X\\Rightarrow Y\\)",
         "\\(X \\subseteq Y\\) iff \\(X\\Rightarrow Y = W\\)",
         "\\(X \\supseteq Y \\) iff \\( X\\Rightarrow Y \\)"
		 ],
 		["Is this true? If for all \\( i\\in I\\), \\( X_i\\) is admissible, then \\( \\bigcap_{i\\in I} X_i\\)." , 2,
         "Yes.",
         "No."
		 ],
  		["What is \\(\\sqcap _{i\\in I} X_i\\)?" , 2,
         "The weakest proposition that entails all of \\( X_i\\)'s.",
         "The weakest admissible proposition that entails all of \\(X_i\\)'s.",
         "The strongest proposition that entails all of \\( X_i\\)'s.",
         "The strongest admissible proposition that entails all of \\( X_i\\)'s.",
         "The weakest proposition entailed by all of \\( X_i\\)'s.",
         "The weakest admissible proposition entailed all of \\(X_i\\)'s.",
         "The strongest proposition entailed by all of \\( X_i\\)'s.",
         "The strongest admissible proposition entailed by all of \\( X_i\\)'s."
		 ],
  		["What is \\(\\bigcap _{i\\in I} X_i\\)?" , 1,
         "The weakest proposition that entails all of \\( X_i\\)'s.",
         "The weakest admissible proposition that entails all of \\(X_i\\)'s.",
         "The strongest proposition that entails all of \\( X_i\\)'s.",
         "The strongest admissible proposition that entails all of \\( X_i\\)'s.",
         "The weakest proposition entailed by all of \\( X_i\\)'s.",
         "The weakest admissible proposition entailed all of \\(X_i\\)'s.",
         "The strongest proposition entailed by all of \\( X_i\\)'s.",
         "The strongest admissible proposition entailed by all of \\( X_i\\)'s."
		 ],
  		["What is \\(\\bigsqcup _{i\\in I} X_i\\)?" , 8,
         "The weakest proposition that entails all of \\( X_i\\)'s.",
         "The weakest admissible proposition that entails all of \\(X_i\\)'s.",
         "The strongest proposition that entails all of \\( X_i\\)'s.",
         "The strongest admissible proposition that entails all of \\( X_i\\)'s.",
         "The weakest proposition entailed by all of \\( X_i\\)'s.",
         "The weakest admissible proposition entailed all of \\(X_i\\)'s.",
         "The strongest proposition entailed by all of \\( X_i\\)'s.",
         "The strongest admissible proposition entailed by all of \\( X_i\\)'s."
		 ],
  		["What is \\(\\bigcup _{i\\in I} X_i\\)?" , 7,
         "The weakest proposition that entails all of \\( X_i\\)'s.",
         "The weakest admissible proposition that entails all of \\(X_i\\)'s.",
         "The strongest proposition that entails all of \\( X_i\\)'s.",
         "The strongest admissible proposition that entails all of \\( X_i\\)'s.",
         "The weakest proposition entailed by all of \\( X_i\\)'s.",
         "The weakest admissible proposition entailed all of \\(X_i\\)'s.",
         "The strongest proposition entailed by all of \\( X_i\\)'s.",
         "The strongest admissible proposition entailed by all of \\( X_i\\)'s."
		 ],
  		["What is the relation between \\(\\sqcap _{i\\in I} X_i\\) and \\(\\bigcap _{i\\in I} X_i\\)?" , 4,
         "They have nothing in common.",
         "They are the same.",
         "They \\(\\sqcap\\) is in the object language, and its meaning is \\(\\bigcap \\) in the meta-language.",
         "\\(\\sqcap _{i\\in I} X_i \\subseteq\\bigcap _{i\\in I} X_i\\).",
         "\\(\\sqcap _{i\\in I} X_i \\supseteq\\bigcap _{i\\in I} X_i\\)."
		 ],
  		["\\(Ea\\)'s are " , 2,
         "always admissible.",
         "sometimes admissible, sometimes not.",
         "never admissible."
		 ],
  		["Goldblatt promises that the commutation principle, CQ: \\(\\forall x \\forall y \\varphi \\rightarrow \\forall y \\forall x \\varphi \\) will be  valid " , 1,
         "if the existence propositions \\(Ea\\)'s are valid.",
         "if the quantified sentences get their Kripkean interpretation, i.e., \\(\\sqcap _{i\\in I} X_i =\\bigcap _{i\\in I} X_i\\)."
		 ],
  		["in complete partial orderings" , 2,
         "every pair of elements have a join and a meet",
         "every set of elements have a join and a meet"
		 ],
  		["What did it mean for Peirce that \\( \pi _ix_i \\)?" , 1,
         "A universally quantified sentence: \\(x_ix_jx_k\\dots\\), where \\(x_i, x_j, x_k\\dots\\) are representatives of sentences about \\(i, j, k, \\dots \\) individuals and multiplication represents conjunction.",
         "An existentially quantified sentence \\(x_i+x_j+x_k+\\dots\\), where \\(x_i, x_j, x_k\\dots\\) are representatives of sentences \\(i, j, k, \\dots \\) individuals and addition represents disjunction."
		 ],
  		["What kind of entity were Mostowski's functionals?" , 3,
         "functions in intuitionistic logic",
		 "variable assignments",
		 "the meanings of a formulas"
		 ],
  		["What is an element of a Lindenbaum(-Tarski) algebra?" , 4,
         "A term",
         "An equation",
         "A formula.",
         "An equivalence class of provably equivalent formulas."
		 ],
  		["In a Lindenbaum(-Tarski) algebra \\(||\\varphi ||\\leq ||\\psi ||\\) iff"  , 1,
         "\\(\\vdash \\varphi \\rightarrow \\psi \\)",
         "\\(||\\varphi ||\\subseteq ||\\psi ||\\)",
         "\\(\\varphi \\subseteq \\psi \\)"
		 ],
  		["What do we know about the quantifiers in a Lindenbaum-Tarski algebra?"  , 2,
         "Since in the Lindenbaum-Tarski algebra every set has a supremum which contains \\(\\forall x \\varphi \\), if the elements of the set contains formulas like \\( \\varphi (y/x)\\) where \\(y \\) is a variable.",
         "Although in the Lindenbaum-Tarski algebra not every set has a supremum, the sets \\( ||\\varphi (y/x)||\\) ,where \\(y \\) is a variable, does have a supremum, precisely \\(||\\forall x \\varphi ||\\).",
		 ],
  		["Basically a cylindric algebra is..."  , 2,
         "a Boolean algebra of valuations.",
         "a Boolean algebra of subsets of the set of valuations."
		 ],
  		["A cylindric algebra is dimension complemented iff for each members \\(b\\) there is some \\(n\\) with \\(\\mathsf c_n b=b\\), roughly speaking,"  , 2,
         "where the cylindric operators fulfil the T-scheme of modal logic: if something is true for all x, then it is true now as well.",
         "where every element/formula have finitely free variables: If it was infinite, then there would be no \\(n\\) such that a quantification could be vacuous."
		 ]
		 ];